### ISSUE TITLE
Where to add the multiple PC name

### ISSUE THREAD

**Issue by Rujinraj** [sbirdsill/PowerShell-PC-Inventory#1]
Where to add the multiple PC name

**Comment by stim-ca** [comment]
From what I understood from the read me, it’s supposed to be run at computer logon via group policy login script. So when any user/computer log in that have that group policy enabled the script will run and output results.

From the read me, it doesn’t seem like this script meant to include remote queries. 

Hopefully this answers your question.

[Microsoft Docs](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn789196(v=ws.11))

**Comment by sbirdsill** [comment]
@stim-ca is correct. This script is intended to be ran on the computer as the logged on user. It does not do remote queries and this is done intentionally. Doing this would require an admin to tweak firewall rules, enable RPC, and potentially perform other measures that could reduce the security footprint. If you need to run remote queries, I'd suggest looking for other scripts that do this, or invest in an RMM software such as Datto or ConnectWise Automate.
