### ISSUE TITLE
Funcionalidad en Win 11

### ISSUE THREAD

**Issue by Rufo51** [sbirdsill/PowerShell-PC-Inventory#3]
Buenas tardes, por lo que veo cuando se ejecuta en Windows 11 no genera el archivo como le puedo hacer. Por otro lado me gustaria saber si lo puedo en red.

**Comment by sbirdsill** [comment]
My apologies, can you clarify the issue in English? I can confirm the script does run on Windows 11 with PowerShell 5.1.

**Comment by arthurpoortman** [comment]
Hi, can you make an option that the script looks in a text file with servernames? Thanks!
